# Generated by Django 2.2.dev20181016201044 on 2018-10-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a product category (e.g. Car, Computer etc.)', max_length=200)),
            ],
        ),
    ]
