# Generated by Django 2.2.dev20181016201044 on 2018-11-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181101_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='blog/%Y/%m/%d'),
        ),
    ]
