# Generated by Django 2.2.dev20181016201044 on 2018-11-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a category', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.ManyToManyField(help_text='Select a catrgory for this post', to='blog.Category'),
        ),
    ]
