# Generated by Django 2.2.dev20181016201044 on 2018-11-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181106_0834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='genre',
            new_name='category',
        ),
    ]
