# Generated by Django 2.2.dev20181016201044 on 2018-11-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181106_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
